### ISSUE TITLE
円弧の長さとまっしろいわーるどの解法

### ISSUE THREAD

**Issue by ss0201** [AI-comp/Orientation2014Problems#1]
お恥ずかしながら「円弧の長さ」と「まっしろいわーるど」の解法がわからないので解説していただけないでしょうか。難易度を決めるうえでも重要なのでお願いします！

**Comment by kohyatoh** [comment]
すみません、今見たらまっしろいわーるどの制約が全探索には大きすぎたので直します。

**Comment by kohyatoh** [comment]
- 円周の長さ
  1. 余弦定理(もしくはベクトルの内積)とacosで角ABCを算出
  2. 円周角の定理で円弧ABCとは反対側の円弧の円周角aを出す
  3. 円弧ABCの円周は円周*(360-a)/360
     (半径は頑張って数式を解いて求める)
- まっしろいわーるど
  全部の順列を調べます (n <= 5に修正しました)

**Comment by ss0201** [comment]
なるほど、ありがとうございます。
