### ISSUE TITLE
暫定問題集

### ISSUE THREAD

**Issue by ss0201** [AI-comp/Orientation2014Problems#2]
現在提案されている問題の難易度等を考慮して、独断ですが問題集を作ってみました。

https://docs.google.com/spreadsheet/ccc?key=0AtEc2RWQ-puxdHo1dENOOEpSbWNhNVdqZG50Vk9TUFE&usp=sharing

１枚目のシートが全問題に対する難易度と備考、２枚目のシートが問題集です。

難易度は、1を起点として、考える要素があれば+2、実装で躓きそうなところがあれば（もしくは実装が重ければ）+1、一般の競技プログラミングで使うアルゴリズムなどが必要になれば難易度5、といった感じで付けています。
雑魚問の中で文字列関係の難易度が少し高いのは去年の様子を見て文字列が苦手そうだからです（実装で+1）。

問題集は難易度曲線やリファレンス関係の制約などを考慮して試しに作ってみたというところです。

とりあえずのたたき台を作ったので、意見等お願いします。

**Comment by junk0612** [comment]
難易度の高い問題が多そうだったので、簡単な問題をいくつか自分の案に追加してみました。
問題数に余裕があるかちょっと微妙ですが、見てもらえるとうれしいです。

**Comment by ss0201** [comment]
問題追加ありがとう。ただ、ほぼ純粋な数学問題が多いので、プログラミングコンテストとしてはどうかな、とちょっと気になった。タイプライターみたいな問題で簡単なのがあると、とてもいいです。
